# Generated by Django 3.2.3 on 2024-08-06 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240805_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество не должно быть меньше 1'), django.core.validators.MaxValueValidator(666666, 'Количество не должно быть больше 666666')], verbose_name='Количество'),
        ),
    ]
