# Generated by Django 3.2.3 on 2024-08-22 16:17

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240822_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Введите название рецепта', max_length=256, validators=[recipes.validators.validate_name], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[recipes.validators.validate_name], verbose_name='Название тега'),
        ),
    ]
