# Generated by Django 3.2.3 on 2024-08-11 13:12

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240807_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, validators=[recipes.validators.validateslug], verbose_name='slug'),
        ),
    ]
