# Generated by Django 3.2.3 on 2024-08-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20240819_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
