# Generated by Django 3.2.3 on 2024-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/user/'),
        ),
    ]
