# Generated by Django 3.2.3 on 2024-08-07 19:28

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_image_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_correct_username, django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Юзернейм'),
        ),
    ]
